default: install-packages set-symlinks

install-packages: 
	./script/install.sh

install-python-packages:
	pip install -r ~/script/python/requirements.txt

set-symlinks:
	ln -s ~/script/shell script

makefile-test:
	@echo "OK" 
