services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: unless-stopped
    ports:
      - "127.0.0.1:6157:6157" # HTTP port
      # - "2222:2222" # SSH port, can be removed if you don't use SSH
    volumes:
      - /home/containers/opengist:/opengist
    environment:
      # OG_LOG_LEVEL: info
      # other configuration options
